[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
openai = "^1.30.5"
reflex = "^0.5.2"
pre-commit = "^3.7.1"
tenacity = "^8.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
